package com.example.authio.persistence;

import androidx.room.PrimaryKey;

import com.google.gson.annotations.SerializedName;

@androidx.room.Entity
public class Entity {
    @PrimaryKey
    @SerializedName("id")
    private int id; // id is fetched from network response - not autogenerated
}
