package com.example.authio.persistence;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.authio.models.CacheModel;
import com.example.authio.shared.Constants;
import com.google.gson.annotations.SerializedName;

/**
 *  Base entity class for all entities
 */
@Entity
public class BaseEntity {
    @PrimaryKey
    @SerializedName(Constants.ID)
    protected int id; // id is fetched from network response - not autogenerated
}
